`yarn add @fortawesome/fontawesome-free` was missing
Not sure what happened there, it likely failed for some reason
on your machine.

I noticed it, when going to the page in the browser opening
the browser console I saw the following error:

> Error: Cannot find module '@fortawesome/fontawesome-free/js/all'